# PANDAS

What is Pandas?
Pandas is a Python library used for:

* Reading datasets
* Cleaning data
* Organizing data
* Filtering data
* Analyzing data
* Preparing data for Machine Learning.

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\Toshiba\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\Toshiba\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Toshiba\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\Users\Toshiba\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\Toshiba\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\Users\Toshiba\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

data = {
    "Product": ["Laptop", "Phone", "Tablet"],
    "Price": [70000, 30000, 25000]
}

df = pd.DataFrame(data)

print(df)

  Product  Price
0  Laptop  70000
1   Phone  30000
2  Tablet  25000

In [6]:
df.head()
df.tail()
df.shape
df.columns
df.dtypes
df.info()
df.describe()
df["Product"]
df[["Product","Price"]]
df.loc[0]
df.loc[0:2]
df.iloc[0]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Product  3 non-null      object
 1   Price    3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

Product    Laptop
Price       70000
Name: 0, dtype: object

In [7]:
import pandas as pd

students = {
    "Name": ["Azeem", "Rahul", "Priya"],
    "Age": [23, 22, 24],
    "Marks": [92, 81, 88]
}

df = pd.DataFrame(students)

print(df)

    Name  Age  Marks
0  Azeem   23     92
1  Rahul   22     81
2  Priya   24     88

In [9]:
print(df.head(1))
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.info())

    Name  Age  Marks
0  Azeem   23     92
(3, 3)
Index(['Name', 'Age', 'Marks'], dtype='object')
Name     object
Age       int64
Marks     int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes
None

In [ ]:
import pandas as pd

df = pd.read_csv("students.csv")

print(df)

In [ ]:
df.to_csv("output.csv", index=False)

In [11]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Azeem", "Rahul", "Priya", "John"],
    "Age": [23, 22, 24, 26],
    "Marks": [92, 81, 88, 75]
})
df[df["Marks"]>80]

    Name  Age  Marks
0  Azeem   23     92
1  Rahul   22     81
2  Priya   24     88

In [12]:
df[(df["Marks"] > 80) & (df["Age"] < 24)]

    Name  Age  Marks
0  Azeem   23     92
1  Rahul   22     81

In [13]:
df[(df["Marks"] > 90) | (df["Age"] < 23)]

    Name  Age  Marks
0  Azeem   23     92
1  Rahul   22     81

In [ ]:
df["Passed"] = df["Marks"] > 80

In [16]:
df["Grade"] = df["Marks"].apply(lambda x: "A" if x > 85 else "B")
print(df)

    Name  Age  Marks  Passed Grade
0  Azeem   23     92    True     A
1  Rahul   22     81    True     B
2  Priya   24     88    True     A
3   John   26     75   False     B

In [ ]:
df.sort_values(by="Marks")

    Name  Age  Marks  Passed Grade
3   John   26     75   False     B
1  Rahul   22     81    True     B
2  Priya   24     88    True     A
0  Azeem   23     92    True     A

In [22]:
df.sort_values(by="Marks", ascending=False)

    Name  Age  Marks  Passed Grade
0  Azeem   23     92    True     A
2  Priya   24     88    True     A
1  Rahul   22     81    True     B
3   John   26     75   False     B

In [23]:
df.drop("Age", axis=1)

    Name  Marks  Passed Grade
0  Azeem     92    True     A
1  Rahul     81    True     B
2  Priya     88    True     A
3   John     75   False     B

In [24]:
df.drop(0)

    Name  Age  Marks  Passed Grade
1  Rahul   22     81    True     B
2  Priya   24     88    True     A
3   John   26     75   False     B

In [ ]:
df.isnull()
df.isnull().sum()
# df.dropna()
# df.fillna()
# df.fillna(df["Marks"].mean)

Name      0
Age       0
Marks     0
Passed    0
Grade     0
dtype: int64

In [27]:
df.groupby("Name")["Marks"].mean()

Name
Azeem    92.0
John     75.0
Priya    88.0
Rahul    81.0
Name: Marks, dtype: float64

In [29]:
df["Name"].value_counts()

Name
Azeem    1
Rahul    1
Priya    1
John     1
Name: count, dtype: int64

In [41]:
df["Marks"].unique()
df["Passed"].unique()

array([ True, False])

In [48]:
n = [10, 20, 4, 20, 8]
s = sorted(set(n))
for i in s:
    largest = s[-1]
    second_largest = s[-2]
print(second_largest)

10

In [53]:
s = "racecar"
n = s[::-1]
if s == n:
    print("Palindrome")
else:
    print("Not Palindrome")

Palindrome

In [54]:
arr = [5, 10, 3, 25, 7]
largest = float('-inf')
for num in arr:
    if num > largest:
        largest = num
print(largest)

25